### ISSUE TITLE
Command 'python manage.py runserver' on error

### ISSUE THREAD

**Issue by jomivz** [ankity10/Mcq-Web-App#5]
(my_virtual_env) ➜  Mcq-Web-App git:(master) python manage.py runserver 8080
base dir path /home/jomivz/my_virtual_env/Mcq-Web-App/static
base dir path /home/jomivz/my_virtual_env/Mcq-Web-App/static
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jomivz/my_virtual_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/jomivz/my_virtual_env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/jomivz/my_virtual_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/home/jomivz/my_virtual_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/jomivz/my_virtual_env/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/jomivz/my_virtual_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jomivz/my_virtual_env/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/jomivz/my_virtual_env/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/jomivz/my_virtual_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'registration'

**Comment by jomivz** [comment]
Django Registration module version 3.0.1 is not compatible with this project.

I did a pull request to specify in requirements.txt the version 2.4.1 based on the a thread in stackoverflow https://stackoverflow.com/questions/52493688/modulenotfounderror-no-module-named-registration :
django-registration==2.4.1

After running the commands : 
1. pip uninstall django-registration
2. pip install django-registration==2.4.1

I was able to run 'python manage.py runserver 8080'
